### ISSUE TITLE
correct answers are not showing after submission

### ISSUE THREAD

**Issue by johnbabu021** [johnbabu021/quiz-app#1]
show a correct answer after submit

**Comment by CH1NRU5T** [comment]
May I work on this issue?

**Comment by johnbabu021** [comment]
Yes you can work on that
Thanks for contributing

**Comment by CH1NRU5T** [comment]
The correct answer should be display below the quiz box after pressing the submit button?

**Comment by johnbabu021** [comment]
I have stored the correct answer in an array

**Comment by CH1NRU5T** [comment]
I can't find that array, but I solved the issue by fetching the correct answer from the api directly when the submit button is pressed. Is that okay?

**Comment by CH1NRU5T** [comment]
Hey, actually I misunderstood the issue. The MAIN issue here is that the question that is being displayed on the page is not correct, the options are correct. 

Just so to confirm, was this the main issue?

Because I thought you wanted something like this: 
![image](https://user-images.githubusercontent.com/72245838/135575519-9ed454ba-c4e5-4996-b265-9db8840d4f15.png)

**Comment by johnbabu021** [comment]
Change the font family

**Comment by johnbabu021** [comment]
Use the one used for question

**Comment by johnbabu021** [comment]
> Hey, actually I misunderstood the issue. The MAIN issue here is that the question that is being displayed on the page is not correct, the options are correct.
> 
> Just so to confirm, was this the main issue?
> 
> Because I thought you wanted something like this: ![image](https://user-images.githubusercontent.com/72245838/135575519-9ed454ba-c4e5-4996-b265-9db8840d4f15.png)

I don't understood what you mean

**Comment by johnbabu021** [comment]
> Hey, actually I misunderstood the issue. The MAIN issue here is that the question that is being displayed on the page is not correct, the options are correct.
> 
> Just so to confirm, was this the main issue?
> 
> Because I thought you wanted something like this: ![image](https://user-images.githubusercontent.com/72245838/135575519-9ed454ba-c4e5-4996-b265-9db8840d4f15.png)


Oh jus

**Comment by CH1NRU5T** [comment]
PR sent! Please do check.

**Comment by johnbabu021** [comment]
Okay

**Comment by johnbabu021** [comment]
Hey @CH1NRU5T 
Please make the changes
Remove new answer ui
And make the correct answer in green color and red for wrong in the question itself
It can be done by settimeout for the whole elements in submit function showing the exact      answer for only 2 seconds

**Comment by CH1NRU5T** [comment]
On it!

**Comment by CH1NRU5T** [comment]
Done @johnbabu021 , PR sent!
