### ISSUE TITLE
Add `hacktoberfest` label

### ISSUE THREAD

**Issue by guptasajal411** [johnbabu021/quiz-app#2]
I noticed that `hacktoberfest` label is missing form this repo, you have shared this in Hacktoberfest Discord server.
![image](https://user-images.githubusercontent.com/70312106/135573676-a7f5ec0e-44af-4cb0-afc3-2d704cb8523f.png)

**Comment by johnbabu021** [comment]
Ok i will add that

**Comment by johnbabu021** [comment]
Now it's added
