### ISSUE TITLE
Using AXIOS instead of Xhttp Object for API requests.

### ISSUE THREAD

**Issue by KryptonANSHU** [johnbabu021/quiz-app#30]
I see this Project has used Xhttp Object for Making Requests.
![Screenshot 2021-10-06 020938](https://user-images.githubusercontent.com/72062616/136099312-2601fe24-30b1-4959-b5cc-c9a309136e13.png)
ee

I plan to replace it with Axios for better Code Efficiency
What do ya say☺

**Comment by johnbabu021** [comment]
Ok you can change
