### ISSUE TITLE
Improve UI on dark mode

### ISSUE THREAD

**Issue by GPrince00** [johnbabu021/quiz-app#31]
Should changes the color of background on dark mode to be better for the user use it

**Comment by johnbabu021** [comment]
Remove box shadow

**Comment by johnbabu021** [comment]
Make a settings page and add your content there like the below image

**Comment by johnbabu021** [comment]
![Screenshot from 2021-09-28 12-41-09](https://user-images.githubusercontent.com/58719884/136158095-d71bb45a-b52a-4ac5-adac-3bde36d22ede.png)

**Comment by johnbabu021** [comment]
![Screenshot from 2021-10-06 12-53-36](https://user-images.githubusercontent.com/58719884/136158209-86ee81e6-b4e2-41aa-a3cc-9d9ec79128ab.png)

**Comment by johnbabu021** [comment]
make the changes like this
don't change the green color for buttons in light theme

**Comment by johnbabu021** [comment]
use purple as default 
in dark 
indigo in black

**Comment by johnbabu021** [comment]
@GPrince00  can you do that

**Comment by GPrince00** [comment]
> @GPrince00 can you do that

Sure. @johnbabu021 Can you create a new issue explaining better and adding the labels of hacktoberfest ?
