### ISSUE TITLE
Correct question not getting displayed.

### ISSUE THREAD

**Issue by CH1NRU5T** [johnbabu021/quiz-app#5]
* In the webpage, the correct question is not getting displayed according to the options provided.
![image](https://user-images.githubusercontent.com/72245838/135578746-4faae5a5-da14-49ac-ac00-93ad0b28f6ab.png)

as we can see in this example, the question given doesn't match the options provided.

**Comment by CH1NRU5T** [comment]
May I work on this issue please?

**Comment by johnbabu021** [comment]
And id from the previous one

**Comment by CH1NRU5T** [comment]
Yes, that needs to be fixed. May I do it?

**Comment by johnbabu021** [comment]
Okay

**Comment by CH1NRU5T** [comment]
PR sent! Please check.
